from __future__ import annotations


def check(question: str, options: list[str], correct: str, explanation: str) -> dict:
    return {"question": question, "options": options, "correct": correct, "explanation": explanation}


DISTANCE_DISPLACEMENT = {
    "status": "production",
    "grade_band": "Grades 7–9",
    "grade_min": 7,
    "grade_max": 9,
    "learning_levels": ["foundation", "standard", "advanced"],
    "estimated_time": "70–90 min",
    "prerequisite_lesson": {"slug": "position-reference-points", "title": "Position and Reference Points"},
    "next_lesson": {"slug": "speed-velocity", "title": "Speed and Velocity", "status": "building"},
    "scientist": {
        "name": "Galileo Galilei",
        "initials": "GG",
        "subtitle": "AI educational representation inspired by Galileo",
        "opening": "Tell me the whole path and the two endpoints; then we can decide what the question measures.",
        "suggested_prompts": [
            "Why can displacement be zero when distance is not?",
            "Check my calculation.",
            "Give me a new number-line example.",
            "Explain negative displacement.",
            "Help me compare these two journeys.",
        ],
    },
    "essential_question": "How can a journey be long even when its displacement is small—or zero?",
    "objectives": [
        "Define distance as total path length and displacement as change in position.",
        "Distinguish scalar distance from displacement with magnitude and direction.",
        "Calculate total distance for direct and multi-stage journeys.",
        "Calculate and interpret Δx = x_f − x_i, including positive, negative, and zero results.",
        "Compare journeys with the same displacement but different distances.",
        "Explain round trips and communicate answers with correct units and directions.",
    ],
    "prerequisites": [
        "Describe position relative to a reference point.",
        "Read positive and negative coordinates on a one-dimensional axis.",
        "Identify an origin and the chosen positive direction.",
        "Subtract signed numbers and use consistent length units.",
    ],
    "prerequisite_review": [
        {"title": "Reference point", "body": "A position is meaningful only relative to a stated reference point. On a coordinate line the reference point assigned 0 is the origin."},
        {"title": "Signed coordinate", "body": "A coordinate combines a number, sign, and unit. Its sign tells which side of the origin the object occupies after a positive direction is chosen."},
        {"title": "Direction convention", "body": "Right is often positive, but it does not have to be. State the convention before interpreting a sign, and keep it unchanged during a calculation."},
        {"title": "Initial and final", "body": "Initial means at the start of the interval; final means at the end. These labels describe order in time, not which number is larger."},
    ],
    "diagnostic": [
        check("Right is positive. A cart begins at −2 m and ends at +3 m. Which are its initial and final positions?", ["xᵢ = −2 m and x_f = +3 m", "xᵢ = +3 m and x_f = −2 m", "Both are +5 m"], "xᵢ = −2 m and x_f = +3 m", "Initial is the starting coordinate and final is the ending coordinate."),
        check("A student walks 4 m right and then 1 m left. What total path length did the student walk?", ["3 m", "4 m", "5 m"], "5 m", "Path length accumulates both parts: 4 m + 1 m."),
        check("What does the negative sign in x = −6 m tell you?", ["The position is impossible", "The object is 6 m opposite the chosen positive direction", "The object traveled −6 m"], "The object is 6 m opposite the chosen positive direction", "A coordinate sign communicates direction from the origin."),
        check("A runner returns to the starting line. Which statement seems most reasonable?", ["The runner moved, but the final and initial positions match", "The runner did not move", "The runner has a negative distance"], "The runner moved, but the final and initial positions match", "A complete trip can end where it began even after a nonzero path."),
        check("Can two routes connect the same start and finish while having different path lengths?", ["Yes", "No", "Only if the origin moves"], "Yes", "Endpoints alone do not specify the route between them."),
    ],
    "vocabulary": [
        {"term": "Distance", "definition": "The total length of the path traveled.", "example": "Walking 5 m out and 5 m back gives 10 m of distance."},
        {"term": "Displacement", "definition": "The signed change in position from the initial position to the final position.", "example": "Moving from 2 m to −1 m gives a displacement of −3 m when right is positive."},
        {"term": "Path", "definition": "The complete route followed during a journey.", "example": "A route around three sides of a field is a path."},
        {"term": "Scalar", "definition": "A quantity described by magnitude and unit without direction.", "example": "A distance of 12 m is a scalar."},
        {"term": "Magnitude", "definition": "The nonnegative size of a quantity.", "example": "The magnitude of a −4 m displacement is 4 m."},
        {"term": "Direction", "definition": "The orientation of a change, stated with words or a sign convention.", "example": "Left, west, and the negative x-direction can describe direction."},
        {"term": "Initial position", "definition": "The coordinate at the start of the journey or interval.", "example": "In Δx = x_f − x_i, x_i is the initial position."},
        {"term": "Final position", "definition": "The coordinate at the end of the journey or interval.", "example": "A walk ending at +7 m has x_f = +7 m."},
        {"term": "Change in position", "definition": "Final position minus initial position; another name for displacement.", "example": "From −2 m to +5 m, the change in position is +7 m."},
        {"term": "Round trip", "definition": "A journey that returns to its starting position.", "example": "One complete lap ending at the starting line is a round trip."},
        {"term": "Coordinate", "definition": "A signed value and unit locating an object relative to an origin.", "example": "x = −3 m is a coordinate."},
        {"term": "Origin", "definition": "The reference point assigned coordinate zero.", "example": "The school door may be chosen as x = 0 m."},
    ],
    "theory_chapters": [
        {
            "number": 1, "heading": "Describing a journey", "lead": "A complete motion story contains both the route and the endpoints.",
            "paragraphs": [
                "Imagine two students leaving the same classroom and meeting at the library. One walks directly along the main corridor. The other detours to a water fountain before arriving. Their starting and ending positions match, but their journeys do not. A useful description therefore records the starting position, ending position, path followed, chosen positive direction, and total path length.",
                "The initial position tells where an object is when the journey begins. The final position tells where it is when the chosen interval ends. Initial does not mean smaller and final does not mean larger. A cart can begin at +8 m and end at +2 m. The labels describe time order, while the signs and numbers describe location.",
                "The path is every part of the route. If a student walks right, turns left, pauses, and walks right again, all three movement segments belong to the path. A map of only the start and finish cannot reveal those reversals. This is why endpoint information and path information answer different questions.",
                "In this lesson we model motion mainly on one straight axis. We state which direction is positive and express every position in the same unit. That simple model lets us separate two quantities: distance, which follows the whole path, and displacement, which compares only the initial and final positions.",
                "A journey record should also preserve order. The coordinate list 0 m, +4 m, and +1 m tells us the traveler reached +4 m before returning to +1 m. Rearranging those same values would describe a different path. A small arrow above each segment can show direction, while labels at the first and last points keep the endpoints clear.",
            ],
            "key_idea": "The route determines distance; the two endpoints determine displacement.",
            "check": check("Which information is needed to know the complete distance traveled?", ["Only initial position", "Only initial and final positions", "Every movement segment of the path"], "Every movement segment of the path", "Distance accumulates the lengths of all segments, including reversals."),
        },
        {
            "number": 2, "heading": "What is distance?", "lead": "Distance measures how much path has been covered.",
            "paragraphs": [
                "Distance is the total length of the path traveled. If you walk 6 m down a corridor and then 2 m back, your distance is 6 m + 2 m = 8 m. We add the length of every segment because your feet covered both segments. The return movement does not erase the effort or the path already traveled.",
                "Distance is a scalar quantity. A scalar has magnitude—a nonnegative size—and a unit, but it does not include direction. A distance answer such as 8 m is complete without saying left or right. Direction still matters when drawing the route, because it helps identify segment lengths, but direction is not part of the final distance quantity.",
                "Distance accumulates while an object moves. A track runner's distance increases around every curve, even when the runner is heading toward the starting line. A person walking among school buildings adds each walkway segment. A toy car that moves forward and backward adds the absolute length of each movement rather than canceling opposite directions.",
                "Because length cannot be negative, distance is normally zero or positive. Zero distance means no path was traveled during the interval. A negative calculator result signals that a coordinate difference was used without taking its magnitude; it does not describe a negative physical path. Common units include centimeters, meters, and kilometers.",
                "When a route contains several stages, calculate one stage at a time. Subtract its two coordinates, take the absolute value, and then add that magnitude to the running total. This procedure works whether both coordinates are positive, both are negative, or the segment crosses the origin. Convert units before adding so every segment uses the same measuring scale.",
            ],
            "formula": "distance = |x₁ − x₀| + |x₂ − x₁| + ⋯ + |xₙ − xₙ₋₁|",
            "key_idea": "Add the nonnegative length of every path segment; opposite movements do not cancel.",
            "check": check("A robot moves 3 m right, 5 m left, then 2 m right. What distance does it travel?", ["0 m", "6 m", "10 m"], "10 m", "Distance adds segment lengths: 3 + 5 + 2 = 10 m."),
        },
        {
            "number": 3, "heading": "What is displacement?", "lead": "Displacement is the change from starting position to ending position.",
            "paragraphs": [
                "Displacement compares the final position with the initial position. It ignores the route between them. If a walker begins at x = 1 m, visits several places, and finishes at x = 6 m, the displacement is +5 m when right is positive. Any other journey with those same endpoints has the same displacement.",
                "Unlike distance, displacement includes direction. In one dimension, a sign can communicate that direction: positive means the chosen positive direction and negative means the opposite. We can also write words, such as 5 m right. Its magnitude is the size without the sign; the magnitude of a −5 m displacement is 5 m.",
                "Displacement can be positive, negative, or zero. It is positive when the final position lies farther in the positive direction than the initial position. It is negative when the final position lies in the negative direction from the initial position. It is zero when initial and final positions are equal, regardless of what happened between them.",
                "Distance and displacement use the same units of length, but they report different features. Saying both are measured in meters does not make them interchangeable. Ask whether the problem requests total route length or overall change in position before choosing a calculation.",
                "A useful sentence frame is: the object has a displacement of [magnitude and unit] in the [direction] direction. This makes the sign physically meaningful instead of leaving it as an unexplained symbol. For zero displacement, no direction is needed because there is no endpoint change to orient.",
            ],
            "key_idea": "Displacement depends only on initial and final position and must be interpreted with direction.",
            "check": check("Which journey information can be removed without changing displacement?", ["Initial position", "Final position", "Details of the route between endpoints"], "Details of the route between endpoints", "Only the initial and final positions enter the displacement calculation."),
        },
        {
            "number": 4, "heading": "Calculating displacement", "lead": "Final minus initial gives the signed change in position.",
            "paragraphs": [
                "The symbol Δ is the Greek capital letter delta and means change in. The equation Δx = x_f − x_i reads: change in position equals final position minus initial position. Here x_i is the initial position, x_f is the final position, and Δx is the displacement. Always subtract in this order, even if the initial number is larger.",
                "If a cart moves from +2 m to +9 m, then Δx = +9 m − (+2 m) = +7 m. Both positions are positive, yet their difference—not their sum—is the displacement. The positive result says the change is 7 m in the chosen positive direction.",
                "If a student moves from +6 m to +1 m, then Δx = +1 m − (+6 m) = −5 m. The negative result is correct: the final position lies 5 m in the negative direction from the start. If both positions are negative, parentheses help. From −8 m to −3 m gives Δx = −3 m − (−8 m) = +5 m.",
                "Crossing the origin needs no special formula. From −4 m to +3 m, Δx = +3 m − (−4 m) = +7 m. The origin lies between the endpoints, so the separation is 4 m + 3 m. If x_f equals x_i, subtraction gives zero, exactly as a round trip requires.",
            ],
            "formula": "Δx = x_f − x_i",
            "key_idea": "Keep the order final minus initial, preserve units, then interpret the sign.",
            "check": check("A cart begins at −6 m and ends at −1 m. What is its displacement?", ["−7 m", "−5 m", "+5 m"], "+5 m", "Δx = −1 − (−6) = +5 m."),
        },
        {
            "number": 5, "heading": "Direction and signs", "lead": "A sign has meaning only after the positive direction is declared.",
            "paragraphs": [
                "Suppose right is positive. Moving from x = +4 m to x = −2 m produces Δx = −6 m, meaning 6 m left. The negative sign is directional information, not a warning and not evidence of a mistake. It must remain attached to displacement until the direction has been stated in words.",
                "A negative displacement is not negative distance. The same direct movement has distance 6 m because path length is a magnitude. For a more complicated trip, distance could be even larger, while displacement remains −6 m as long as the endpoints stay +4 m and −2 m.",
                "Now reverse the coordinate convention so left is positive without moving anything. Every coordinate changes sign. The journey formerly described as −6 m becomes +6 m in the new convention. The physical route, endpoint separation, and distance stay unchanged. Only the signed language used to describe direction changes.",
                "This connects directly to reference points from Lesson 1. Coordinates depend on the chosen origin and axis direction. If the origin is shifted, both endpoint coordinates change by the same amount, so their difference remains the same. If axis orientation reverses, the sign of displacement reverses but its magnitude does not.",
            ],
            "key_idea": "Negative displacement means change opposite the chosen positive direction; distance remains nonnegative.",
            "check": check("Only the positive direction is reversed. What changes?", ["The physical path", "The displacement sign", "The distance traveled"], "The displacement sign", "Axis reversal relabels direction but does not change the physical journey."),
        },
        {
            "number": 6, "heading": "Same displacement, different distance", "lead": "Matching endpoints do not guarantee matching routes.",
            "paragraphs": [
                "Journey A goes directly from 0 m to +6 m. Its distance is 6 m and its displacement is +6 m. Journey B goes from 0 m to +10 m and then back to +6 m. Its distance is 10 m + 4 m = 14 m, while its displacement is still +6 m.",
                "The equal displacements occur because both journeys share x_i = 0 m and x_f = +6 m. The extra turn in Journey B affects the path but not the endpoints. This comparison shows why displacement cannot be found by adding every unsigned path length.",
                "For one-dimensional motion, distance is always at least as large as displacement magnitude. A direct journey without reversing direction makes them equal in magnitude. Detours and reversals add path length, so distance becomes greater. Signed displacement itself may be negative, so compare distance with |Δx| rather than with the signed number.",
                "This distinction matters in planning routes. Two hallways may lead from the same classroom to the same laboratory, but one may be longer. Their start-to-finish displacement is identical, while the walking distances differ. Displacement captures overall change; distance captures the route's accumulated length.",
            ],
            "key_idea": "Same endpoints mean same displacement, but different routes can produce different distances.",
            "check": check("From 0 m, one route goes to +8 m and back to +5 m. What are distance and displacement?", ["5 m and +5 m", "11 m and +5 m", "13 m and +5 m"], "11 m and +5 m", "Distance is 8 + 3 = 11 m; displacement is 5 − 0 = +5 m."),
        },
        {
            "number": 7, "heading": "Round trips", "lead": "Returning to the start erases displacement, not traveled distance.",
            "paragraphs": [
                "A round trip ends at its starting position. A runner completes one lap and returns to the line. A shopper walks from home to a store and back. A cart rolls forward and is pulled to its original mark. In every case x_f = x_i, so Δx = 0.",
                "Zero displacement does not mean the object did not move. The runner covered a full track, the shopper covered the outward and return paths, and the cart covered both movements. Their distances are positive because path was traveled. Zero reports only that there is no net change between endpoints.",
                "Consider a cart starting at +2 m, moving to +9 m, and returning to +2 m. Its distance is |9 − 2| + |2 − 9| = 7 m + 7 m = 14 m. Its displacement is +2 m − (+2 m) = 0 m. The origin did not need to be the starting point.",
                "Round trips provide a powerful check on reasoning. If a route finishes at its start and a calculation gives nonzero displacement, recheck the endpoint labels or subtraction. If a moving object returns and the distance calculation gives zero, the signed segments were incorrectly allowed to cancel.",
            ],
            "key_idea": "A round trip has zero displacement and positive distance whenever motion occurred.",
            "check": check("A runner completes one 400 m lap and stops at the starting line. Which pair is correct?", ["distance 0 m, displacement 400 m", "distance 400 m, displacement 0 m", "distance 400 m, displacement 400 m"], "distance 400 m, displacement 0 m", "The runner covers 400 m of path and finishes at the initial position."),
        },
        {
            "number": 8, "heading": "Representing and extending journeys", "lead": "Words, number lines, route tables, and diagrams should tell the same physics story.",
            "paragraphs": [
                "A word description states movements and directions. A number-line diagram marks the ordered positions. A route table lists x₀, x₁, x₂, and later points. Each representation should preserve segment order. From the table, subtract neighboring positions and take absolute values for distance; compare only the first and last for displacement.",
                "A displacement arrow points directly from the initial position to the final position. It does not trace every turn. On a one-dimensional diagram it may lie over the same axis as the route, but its direction and endpoint make it distinct. The traveled path can be drawn with separate colored segments or arrows.",
                "This lesson focuses on one dimension, which is appropriate for corridors, straight roads, and number lines. In two dimensions, distance still follows the actual path, while the displacement arrow connects start directly to finish. Grade 9 students may explore that conceptual extension, but the core pathway does not require the Pythagorean theorem.",
                "These ideas prepare us for speed. Later, time will be connected to how much path or change in position occurs. For now, keep the focus on describing the journey correctly: path length for distance, final minus initial for displacement, and clear units and direction in every interpretation.",
            ],
            "key_idea": "Different representations are useful only when they preserve route order, endpoints, units, and direction convention.",
            "check": check("In a journey diagram, what should a displacement arrow connect?", ["Every turning point", "Initial position directly to final position", "The origin to the longest segment"], "Initial position directly to final position", "Displacement represents overall endpoint change, not the route."),
        },
    ],
    "additional_checks": [
        check("True or false: distance and displacement always have the same magnitude.", ["True", "False"], "False", "They match only for a direct one-direction journey."),
        check("A journey has displacement −4 m. What is its displacement magnitude?", ["−4 m", "0 m", "4 m"], "4 m", "Magnitude is nonnegative; the sign separately communicates direction."),
    ],
    "video": {
        "title": "Why Going Far Does Not Always Mean Large Displacement",
        "target_duration": "6–9 minutes",
        "status": "in production",
        "storyboard": [
            "Hook: walk a long loop and ask why the final displacement is zero.",
            "Lay floor tape as a corridor number line and define the positive direction.",
            "Walk directly forward; compare path length with endpoint change.",
            "Walk forward and backward; pause so students predict both quantities.",
            "Complete a round trip and contrast nonzero distance with zero displacement.",
            "Build Δx = x_f − x_i symbol by symbol beside the physical demonstration.",
            "Correct the claim that a negative displacement means negative distance.",
            "Preview the Journey Lab and close with a two-route comparison challenge.",
        ],
        "filming_notes": [
            "Keep start, finish, and turning points visible throughout each calculation.",
            "Use one consistent meter scale and state right-positive on screen.",
            "Pause for predictions before revealing distance and displacement.",
            "Label the file as in production until real recorded media is approved.",
        ],
    },
    "simulation": {
        "type": "distance_displacement_journey",
        "title": "Journey Lab: Distance vs. Displacement",
        "instruction": "Build a multi-stage route, predict what will happen, then animate and compare the traveled path with the displacement arrow.",
        "tasks": [
            "Create a journey where distance equals displacement magnitude.",
            "Create a journey where distance is greater than displacement magnitude.",
            "Create a journey with zero displacement and nonzero distance.",
            "Save two journeys with equal displacement but different distances.",
            "Reverse the positive direction and observe which sign changes.",
        ],
    },
    "worked_examples": [
        {"title": "Example 1: Direct positive movement", "question": "Ava walks from +1 m to +7 m.", "known": "x_i = +1 m; x_f = +7 m; direct route", "steps": ["Distance is the direct path length: |7 − 1| = 6 m.", "Displacement is final minus initial: Δx = 7 − 1 = +6 m.", "The positive sign means right under the stated convention."], "answer": "distance = 6 m; displacement = +6 m (right)", "reasoning": "No reversal occurred, so distance equals displacement magnitude.", "common_error": "Do not add the two coordinates."},
        {"title": "Example 2: Direct negative movement", "question": "Ben walks from +5 m to −2 m.", "known": "x_i = +5 m; x_f = −2 m", "steps": ["Distance is |−2 − 5| = 7 m.", "Δx = −2 − (+5) = −7 m.", "Negative means 7 m left, not negative distance."], "answer": "distance = 7 m; displacement = −7 m (left)", "reasoning": "The direct path has length 7 m and its direction is negative.", "common_error": "Keep parentheses around the signed initial position."},
        {"title": "Example 3: Crossing the origin", "question": "A cart moves from −4 m to +3 m.", "known": "The origin lies between endpoints.", "steps": ["The path has 4 m to the origin and 3 m beyond it.", "Distance = 4 + 3 = 7 m.", "Δx = +3 − (−4) = +7 m."], "answer": "distance = 7 m; displacement = +7 m", "reasoning": "Crossing zero uses the same final-minus-initial rule.", "common_error": "Subtracting magnitudes as 4 − 3 ignores the positions' signs."},
        {"title": "Example 4: Multi-stage movement", "question": "Move 0 m → +8 m → +3 m → +6 m.", "known": "Ordered positions: 0, 8, 3, 6 m", "steps": ["Segment lengths are 8 m, 5 m, and 3 m.", "Distance = 8 + 5 + 3 = 16 m.", "Displacement = 6 − 0 = +6 m."], "answer": "distance = 16 m; displacement = +6 m", "reasoning": "Distance uses every segment; displacement uses first and last only.", "common_error": "Signed movements may sum to displacement, but not to distance."},
        {"title": "Example 5: Round trip", "question": "A robot starts at +2 m, visits −3 m, and returns to +2 m.", "known": "The final position equals the initial position.", "steps": ["Each leg is 5 m.", "Distance = 5 + 5 = 10 m.", "Δx = +2 − (+2) = 0 m."], "answer": "distance = 10 m; displacement = 0 m", "reasoning": "The route is nonzero even though endpoint change is zero.", "common_error": "Zero displacement does not mean zero movement."},
        {"title": "Example 6: Same endpoints, different routes", "question": "Compare 0 → +6 with 0 → +10 → +6.", "known": "Both start at 0 m and finish at +6 m.", "steps": ["Direct-route distance is 6 m.", "Detour distance is 10 + 4 = 14 m.", "Both displacements are 6 − 0 = +6 m."], "answer": "distances 6 m and 14 m; both displacements +6 m", "reasoning": "Endpoints control displacement while the route controls distance.", "common_error": "Matching displacement does not prove matching distance."},
        {"title": "Example 7: Grade 9 coordinate reversal", "question": "A journey is +3 m to −5 m when right is positive. Re-describe it when left is positive.", "known": "Physical endpoints stay fixed; orientation reverses.", "steps": ["Right-positive displacement is −5 − 3 = −8 m.", "Reversing the axis changes both coordinate signs.", "New displacement is +8 m; distance remains 8 m."], "answer": "left-positive displacement = +8 m; distance = 8 m", "reasoning": "Axis orientation changes signed description, not physical separation.", "common_error": "Do not move the objects when relabeling the axis."},
    ],
    "misconceptions": [
        {"myth": "Distance and displacement are always equal.", "why": "They match on a direct one-way trip.", "correction": "They differ after a reversal or detour.", "example": "0 → 10 → 6 has distance 14 m and displacement +6 m.", "quick_check": "Would one full lap make them equal?"},
        {"myth": "Displacement is the total path length.", "why": "Both use length units.", "correction": "Displacement uses only final minus initial position.", "example": "A 400 m lap has 0 m displacement.", "quick_check": "Which quantity needs every segment?"},
        {"myth": "A negative displacement is impossible.", "why": "Physical lengths are nonnegative.", "correction": "The sign communicates direction.", "example": "From +2 m to −3 m gives −5 m.", "quick_check": "What direction does negative mean here?"},
        {"myth": "Negative displacement means negative distance.", "why": "The same trip produces both quantities.", "correction": "Distance is the nonnegative path length.", "example": "A direct −5 m displacement has 5 m distance.", "quick_check": "Which answer keeps a sign?"},
        {"myth": "Zero displacement means the object did not move.", "why": "No endpoint change sounds like no motion.", "correction": "A round trip can contain a long path.", "example": "Home → store → home has zero displacement.", "quick_check": "Can its distance be positive?"},
        {"myth": "The origin must be the starting position.", "why": "Diagrams often choose it for convenience.", "correction": "Any useful fixed reference can be origin.", "example": "A cart can start at +4 m and return there.", "quick_check": "What is its round-trip displacement?"},
        {"myth": "A longer journey must have a larger displacement.", "why": "Both quantities involve length.", "correction": "Extra turns increase distance without changing endpoints.", "example": "Two routes to the same door share displacement.", "quick_check": "What controls displacement?"},
    ],
    "guided_practice": [
        {"question": "From +2 m to +9 m, find displacement.", "hints": ["Identify x_i and x_f.", "The question asks for endpoint change.", "Use Δx = x_f − x_i.", "Calculate 9 − 2.", "Interpret the positive sign with units."]},
        {"question": "From +4 m to −1 m, find distance for a direct path.", "hints": ["Mark both endpoints.", "A direct path has one segment.", "Use the absolute coordinate difference.", "Calculate |−1 − 4|.", "Distance has no direction."]},
        {"question": "Route 0 → 5 → 2 m: find both quantities.", "hints": ["List segment endpoints.", "Distance needs both segment lengths.", "Add |5−0| and |2−5|.", "Displacement uses 2−0.", "Compare distance with |Δx|."]},
        {"question": "Route −3 → +2 → −3 m: explain the result.", "hints": ["Compare initial and final.", "This is a round trip.", "Calculate each segment length.", "Subtract final minus initial.", "Explain why movement still occurred."]},
        {"question": "Two routes 0 → 6 and 0 → 9 → 6: compare.", "hints": ["Check shared endpoints.", "Equal endpoints imply equal displacement.", "Find each route length.", "Keep distance separate.", "State the comparison in a sentence."]},
        {"question": "A displacement is −7 m when right is positive. Interpret it.", "hints": ["A sign communicates direction.", "Negative is opposite right.", "The magnitude is 7 m.", "Use the word left.", "Do not call distance negative."]},
        {"question": "A cart starts and ends at +5 m after moving. What is Δx?", "hints": ["Write x_i and x_f.", "They are equal.", "Subtract 5 − 5.", "Do not infer path length.", "Explain what zero does and does not mean."]},
        {"question": "Positions are −8, −2, −5 m. Find distance.", "hints": ["Keep the order.", "Find |-2−(-8)|.", "Find |-5−(-2)|.", "Add both magnitudes.", "Include meters."]},
        {"question": "Reverse positive direction for a +4 m displacement.", "hints": ["The physical journey is fixed.", "Axis reversal reverses signs.", "Magnitude is unchanged.", "Distance is unchanged.", "State the new signed displacement."]},
        {"question": "Explain why distance ≥ |displacement| in one dimension.", "hints": ["Imagine the direct endpoint route.", "That direct length is |Δx|.", "Turns add extra path.", "They cannot subtract from distance.", "Write a complete comparison."]},
    ],
    "practice_groups": [
        {"level": "Foundation", "description": "Visual and direct integer-coordinate journeys.", "questions": ["Define distance in your own words and name its unit.", "Define displacement and explain why direction matters.", "Find displacement from 1 m to 7 m.", "Find direct distance from 5 m to −1 m.", "A student walks 3 m right then 2 m left. Find total distance.", "For the same journey, find displacement."]},
        {"level": "Standard", "description": "Signed coordinates and multi-stage routes.", "questions": ["Find distance and displacement for −2 → +6 → +1 m.", "Compare routes 0 → 8 m and 0 → 11 → 8 m.", "A cart starts at −5 m and finishes at −9 m. Interpret Δx.", "Create a three-stage round trip with distance 12 m.", "Explain the error in adding signed segments to find distance.", "Draw a route with distance 10 m and displacement +4 m."]},
        {"level": "Challenge", "description": "Coordinate reversal, justification, and conceptual extension.", "questions": ["Re-describe −3 → +4 m after reversing the positive direction.", "Two journeys have distance 18 m. Must their displacement magnitudes match? Justify.", "A route table is −4, +1, −2, +3 m. Calculate both quantities.", "Sketch two two-dimensional paths with equal endpoints and compare conceptually without calculation.", "Explain why moving the origin does not change Δx."]},
    ],
    "quiz": [
        {"id": "ddq1", "type": "multiple_choice", "objective": "distance_definition", "question": "Which statement defines distance?", "options": ["Final position minus initial position", "Total length of the traveled path", "Direction from origin"], "correct": "Total length of the traveled path"},
        {"id": "ddq2", "type": "multiple_choice", "objective": "scalar_vector", "question": "Which comparison is correct?", "options": ["Distance is scalar; displacement includes direction", "Both are scalars", "Distance includes direction; displacement does not"], "correct": "Distance is scalar; displacement includes direction"},
        {"id": "ddq3", "type": "multiple_choice", "objective": "round_trip", "question": "A runner completes one lap and stops at the start. Which is true?", "options": ["Both quantities are zero", "Distance is positive and displacement is zero", "Distance is zero and displacement is positive"], "correct": "Distance is positive and displacement is zero"},
        {"id": "ddq4", "type": "numerical", "objective": "calculate_displacement", "question": "Right is positive. Find Δx for x_i = −4 m and x_f = +3 m.", "options": ["+7 m", "−7 m", "+1 m"], "correct": "+7 m"},
        {"id": "ddq5", "type": "numerical", "objective": "calculate_distance", "question": "Find distance for 0 → +8 → +3 m.", "options": ["3 m", "8 m", "13 m"], "correct": "13 m"},
        {"id": "ddq6", "type": "numerical", "objective": "negative_displacement", "question": "Find Δx for +6 m to −2 m.", "options": ["−8 m", "+8 m", "4 m"], "correct": "−8 m"},
        {"id": "ddq7", "type": "route_analysis", "objective": "compare_routes", "question": "Which route has displacement +5 m and distance 11 m?", "options": ["0 → +5", "0 → +8 → +5", "−5 → 0"], "correct": "0 → +8 → +5"},
        {"id": "ddq8", "type": "route_analysis", "objective": "multi_stage", "question": "For −2 → +4 → −2 m, which pair is correct?", "options": ["distance 12 m; displacement 0 m", "distance 0 m; displacement 12 m", "distance 6 m; displacement −4 m"], "correct": "distance 12 m; displacement 0 m"},
        {"id": "ddq9", "type": "written_review", "objective": "explain_zero", "question": "Explain how zero displacement can occur after motion.", "options": ["Written response — reviewed separately"], "correct": None, "review_note": "Awaiting educator review"},
        {"id": "ddq10", "type": "written_review", "objective": "explain_sign", "question": "Explain what negative displacement means and why it is not negative distance.", "options": ["Written response — reviewed separately"], "correct": None, "review_note": "Awaiting educator review"},
    ],
    "mastery_threshold": 80,
    "homework": {
        "title": "Distance and Displacement Homework",
        "estimated_time": "25–35 min",
        "status": "Workspace coming soon",
        "due_date": None,
        "workspace_available": False,
        "metadata": {"lesson_slug": "distance-displacement", "assignment_key": "distance-displacement-homework"},
    },
    "summary": [
        "Distance measures total path length and is a nonnegative scalar.",
        "Displacement measures change in position and includes direction.",
        "Calculate signed displacement with Δx = x_f − x_i.",
        "Distance never becomes negative; displacement may be positive, negative, or zero.",
        "Different routes can have the same displacement and different distances.",
        "A round trip has zero displacement but positive distance when movement occurred.",
        "Displacement magnitude is |Δx| and must not be confused with signed displacement.",
    ],
    "reflection": "Describe a journey from your own life where the distance traveled is greater than the magnitude of displacement.",
}
