from __future__ import annotations


def check(question: str, options: list[str], correct: str, explanation: str) -> dict:
    return {"question": question, "options": options, "correct": correct, "explanation": explanation}


SPEED = {
    "status": "production",
    "grade_band": "Grades 7–9",
    "grade_min": 7,
    "grade_max": 9,
    "learning_levels": ["foundation", "standard", "advanced"],
    "estimated_time": "70–90 min",
    "prerequisite_lesson": {"slug": "distance-displacement", "title": "Distance and Displacement"},
    "next_lesson": {"slug": "velocity", "title": "Velocity", "status": "building"},
    "scientist": {
        "name": "Richard Feynman",
        "initials": "RF",
        "portrait": "brand/feynman-guide.svg",
        "subtitle": "AI educational representation inspired by Richard Feynman",
        "opening": "Tell me what distance and time you know. We will make the relationship understandable before calculating.",
        "suggested_prompts": [
            "Why do we divide distance by time?", "Check my speed calculation.",
            "How do I find distance instead?", "Does a rest count in total time?",
            "Why can two journeys have the same average speed?", "Explain speed versus velocity.",
        ],
    },
    "essential_question": "How can distance and time be combined to compare how fast different motions are?",
    "objectives": [
        "Define scalar speed as the rate at which distance is traveled.",
        "Use v = d/t and rearrange it to d = vt and t = d/v.",
        "Select consistent units and interpret m/s, km/h, and mph.",
        "Calculate average speed from total distance and total elapsed time, including stops.",
        "Compare realistic motions and identify unreasonable answers.",
        "Distinguish speed from distance, displacement, and the directional quantity velocity.",
    ],
    "prerequisites": [
        "Distinguish total distance from displacement.", "Add the lengths of every stage of a journey.",
        "Use length units consistently.", "Divide and multiply positive numbers.",
    ],
    "prerequisite_review": [
        {"title": "Distance, not displacement", "body": "Speed uses total path length. Revisit Lesson 2 Theory 2 if you need to review how every segment is accumulated."},
        {"title": "Scalar quantity", "body": "Distance has magnitude without direction. Speed is also scalar: its value tells how fast, not which way."},
        {"title": "Complete journey", "body": "For a multi-stage route, add every distance. Later, average speed will compare that total with the complete elapsed time."},
        {"title": "Units of length and time", "body": "A calculation is meaningful only when values use compatible units, such as meters with seconds or kilometers with hours."},
    ],
    "diagnostic": [
        check("A runner completes one 400 m lap. Which value is the distance?", ["0 m", "400 m", "The runner's direction"], "400 m", "Distance is the total path length, even when displacement is zero."),
        check("A bus travels 3 km east and 2 km west. Which quantity belongs in a speed calculation?", ["5 km distance", "1 km displacement", "East"], "5 km distance", "Speed uses total distance, not displacement."),
        check("A toy car travels for 45 seconds. Which quantity is 45 s?", ["Distance", "Elapsed time", "Speed"], "Elapsed time", "Seconds measure time."),
        check("What is 24 divided by 6?", ["4", "18", "144"], "4", "Speed calculations require division of distance by time."),
        check("Which is a possible speed unit?", ["m/s", "m × s", "s/m²"], "m/s", "A speed unit is a distance unit divided by a time unit."),
    ],
    "vocabulary": [
        {"term": "Speed", "definition": "The rate at which distance is traveled.", "example": "6 m/s means 6 meters are covered each second."},
        {"term": "Rate", "definition": "A comparison showing how one quantity changes for each unit of another.", "example": "Meters per second compares distance with time."},
        {"term": "Distance", "definition": "The total length of the traveled path.", "example": "Out 8 m and back 3 m gives 11 m."},
        {"term": "Time", "definition": "The duration of an event or journey.", "example": "A trip lasting 25 s has 25 s elapsed time."},
        {"term": "Average speed", "definition": "Total distance divided by total elapsed time.", "example": "100 m in 20 s averages 5 m/s."},
        {"term": "Total distance", "definition": "The sum of every traveled path segment.", "example": "2 km + 3 km = 5 km total."},
        {"term": "Elapsed time", "definition": "All time from the start to finish, including stops when the complete journey is measured.", "example": "Ten moving minutes plus five resting minutes is 15 min elapsed."},
        {"term": "Constant speed", "definition": "Speed that stays unchanged during an interval.", "example": "A belt moving steadily at 2 m/s."},
        {"term": "Changing speed", "definition": "Motion whose speed is not the same throughout.", "example": "A bus slowing for a stop."},
        {"term": "Instantaneous speed", "definition": "Speed at one particular moment.", "example": "A speedometer reading now."},
        {"term": "Scalar", "definition": "A quantity with magnitude and unit but no direction.", "example": "Speed is scalar."},
        {"term": "Meters per second", "definition": "Meters traveled during each second at the stated rate.", "example": "m/s."},
        {"term": "Kilometers per hour", "definition": "Kilometers traveled during each hour at the stated rate.", "example": "km/h."},
        {"term": "Miles per hour", "definition": "Miles traveled during each hour at the stated rate.", "example": "mph."},
    ],
    "theory_chapters": [
        {
            "number": 1, "heading": "What does “fast” mean?", "lead": "A fair comparison needs both distance and time.",
            "paragraphs": [
                "Two students race from one end of a 30 m corridor to the other. Lena arrives in 6 s and Marco arrives in 10 s. They covered the same distance, so the shorter time identifies Lena as faster. Saying only that both traveled 30 m cannot tell us who moved faster; distance alone leaves out how long the motion took.",
                "Now imagine two toy cars moving for the same 5 s. The blue car covers 20 m while the orange car covers 12 m. Because their times match, the car that covers more distance is faster. Time alone is also insufficient: knowing that both moved for 5 s does not reveal how much ground either covered.",
                "The word faster therefore describes a relationship. We compare how much distance is covered during an amount of time. A cyclist can cover more ground than a pedestrian during one minute, and a runner can finish the same track distance sooner than another runner. Both comparisons combine distance with time.",
                "A fair comparison must also use compatible units and the same interval idea. Comparing 100 m in seconds with 2 km in minutes requires conversion or a calculated rate. Speed gives one number that summarizes this comparison, allowing school walkers, buses, runners, and toy cars to be discussed using the same reasoning.",
            ],
            "key_idea": "Greater distance in the same time, or the same distance in less time, means greater speed.",
            "check": check("Two cyclists ride for 20 s. A covers 100 m and B covers 80 m. Who is faster?", ["A", "B", "Cannot tell"], "A", "With equal times, the greater distance means the greater speed."),
        },
        {
            "number": 2, "heading": "Defining speed", "lead": "Speed is the rate at which distance is traveled.",
            "paragraphs": [
                "A rate compares one quantity with another using the word per. Speed compares distance per unit time. If a cart moves at 4 meters per second, then at that steady rate it covers 4 m during each second. The number does not simply report a distance or a time; it describes how rapidly distance accumulates.",
                "Greater speed means distance accumulates more quickly. During the same ten seconds, an object at 6 m/s covers more distance than one at 2 m/s. For the same 24 m journey, the object with greater speed needs less time. These are two views of the same relationship rather than separate rules to memorize.",
                "Speed is a scalar quantity. It has a nonnegative magnitude and a unit, but direction is not part of it. A car may travel east or west at 15 m/s; its speed is 15 m/s in both cases. Direction will matter when the later lesson introduces velocity, but it does not belong in a speed answer.",
                "A stationary object has speed zero because it adds no distance during the interval. It does not have negative speed. Reversing direction can add to distance traveled, but the scalar speed remains zero or positive. Always separate the path length used for speed from the signed displacement studied in Lesson 2.",
            ],
            "key_idea": "Speed tells how many units of distance are covered per unit of time and has no direction.",
            "check": check("Which statement is a complete speed?", ["8 m east", "8 m/s", "8 seconds"], "8 m/s", "Speed combines distance per time and does not include direction."),
        },
        {
            "number": 3, "heading": "The speed formula", "lead": "Dividing distance by time finds distance per unit time.",
            "paragraphs": [
                "The relationship is written speed = distance ÷ time, or v = d/t. In this lesson v labels scalar speed because many introductory textbooks use that symbol. Other books reserve v for velocity. The surrounding words and units must make clear which quantity is meant; here direction is not included.",
                "In the fraction, distance d is the numerator and time t is the denominator. Dividing a 30 m path by 6 s asks how many meters belong to each one second. The result is 5 m/s. This meaning matters more than a formula triangle because it explains why division is the correct operation.",
                "Every calculation should identify the physical quantities before substituting numbers. Write d = 30 m and t = 6 s, then v = d/t = 30 m/6 s = 5 m/s. Keeping labels and units visible prevents distance from being confused with displacement and makes an incorrect operation easier to notice.",
                "A reasonableness check completes the solution. If 30 m takes 6 s, a result of 180 m/s is unreasonable because multiplication was used instead of division. Multiplying 5 m/s by 6 s returns 30 m, confirming that the rate and time reproduce the original distance.",
            ],
            "formula": "v = d / t",
            "key_idea": "Division shares the total distance across the total time.",
            "check": check("A cart travels 28 m in 7 s. What is its speed?", ["4 m/s", "21 m/s", "196 m/s"], "4 m/s", "v = 28 ÷ 7 = 4 m/s."),
        },
        {
            "number": 4, "heading": "Units of speed", "lead": "The input units determine the rate unit.",
            "paragraphs": [
                "Meters divided by seconds produces meters per second, written m/s. A speed of 5 m/s means five meters are covered during each second at that rate. Kilometers divided by hours produces km/h, while miles divided by hours produces mph. The slash is read per and represents division.",
                "Distance and time values must be compatible before calculation. Dividing 600 m by 2 minutes gives 300 m/min, which is valid, but it is not yet m/s. Converting 2 minutes to 120 seconds gives 600 m ÷ 120 s = 5 m/s. Never silently treat minutes as seconds.",
                "Useful conversions include 60 s = 1 min, 60 min = 1 h, 1000 m = 1 km, and 1 km = 1000 m. Choose a target unit, convert each input to matching distance and time units, and only then use the formula. Write conversion steps so factors are visible.",
                "For the Grade 9 extension, 1 m/s equals 3.6 km/h. One hour contains 3600 seconds, so an object covering 1 m each second covers 3600 m, or 3.6 km, in one hour. Multiply m/s by 3.6 to obtain km/h; divide km/h by 3.6 to return to m/s.",
            ],
            "key_idea": "Convert before calculating, then preserve the distance-per-time unit.",
            "check": check("Kilometers divided by hours gives which unit?", ["km/h", "m/s", "h/km"], "km/h", "The numerator and denominator units follow the formula."),
        },
        {
            "number": 5, "heading": "Solving for speed", "lead": "Organize known values before dividing.",
            "paragraphs": [
                "Use a repeatable method: identify distance, identify time, check units, write v = d/t, substitute, calculate, attach the unit, and judge the result. A runner covering 120 m in 24 s has v = 120 m ÷ 24 s = 5 m/s. Each written step answers a specific reasoning question.",
                "The distance must be total path length. If a student walks 30 m out and 10 m back in 20 s, the distance is 40 m, not the 20 m displacement magnitude. Average speed is 40 m ÷ 20 s = 2 m/s. Using displacement would answer a different future question about average velocity.",
                "Decimal results can be appropriate. A robot traveling 15 m in 4 s has speed 3.75 m/s. Do not round too early; retain the calculator value until the final line, then use the precision requested or a sensible number of significant figures for advanced work.",
                "Estimate before calculating. Fifteen meters in about four seconds should be a little less than four meters each second, so 3.75 m/s is plausible. An answer of 0.27 m/s comes from reversing the division, and 60 m/s comes from multiplying.",
            ],
            "key_idea": "Use total distance divided by total time and finish with a reasonableness check.",
            "check": check("A walker covers 18 m in 12 s. What is the speed?", ["0.67 m/s", "1.5 m/s", "216 m/s"], "1.5 m/s", "18 ÷ 12 = 1.5 m/s."),
        },
        {
            "number": 6, "heading": "Solving for distance", "lead": "Distance equals speed multiplied by time.",
            "paragraphs": [
                "If speed and time are known, rearrange v = d/t to d = vt. Multiplying both sides by t cancels the division by time. Conceptually, an object covering 3 m during each second covers 3 m/s × 8 s = 24 m during eight seconds.",
                "Write the known values and check that their units match. A bus moving at 50 km/h for 2 h travels d = 50 km/h × 2 h = 100 km. The hour units cancel, leaving kilometers. Units help confirm that multiplication produces a distance.",
                "For a fraction of an hour, preserve the same reasoning. A cyclist at 12 km/h for 0.5 h travels 6 km. Alternatively, convert thirty minutes to 0.5 h first. Using 30 as though it were hours would produce an obviously unreasonable result.",
                "The formula describes constant speed directly and can also use an average speed when the question asks only for total distance over an interval. State which interpretation is being used. Do not add a direction to distance because distance remains scalar path length.",
            ],
            "formula": "d = vt",
            "key_idea": "A per-time rate multiplied by the number of time units gives total distance.",
            "check": check("At 4 m/s for 9 s, how far does an object travel?", ["2.25 m", "13 m", "36 m"], "36 m", "d = 4 × 9 = 36 m."),
        },
        {
            "number": 7, "heading": "Solving for time", "lead": "Time equals distance divided by speed.",
            "paragraphs": [
                "To find duration, rearrange the relationship to t = d/v. A walker who must cover 60 m at 3 m/s needs 60 m ÷ 3 m/s = 20 s. The question asks how many groups of three meters fit into the sixty-meter route, with each group corresponding to one second.",
                "Division by speed is sensible because greater speed reduces the time for a fixed distance. If speed doubles from 3 m/s to 6 m/s while distance remains 60 m, the time halves from 20 s to 10 s. This inverse pattern provides a useful check.",
                "Speed must be greater than zero when calculating travel time from this formula. Dividing by zero is undefined. A stationary object will never complete a nonzero target distance unless its motion changes, so the mathematical restriction matches the physical situation.",
                "Keep units consistent. A 90 km trip at 45 km/h takes 2 h. If distance is in meters and speed in kilometers per hour, convert one of them before dividing. The remaining unit after cancellation should be a time unit.",
            ],
            "formula": "t = d / v",
            "key_idea": "Distance divided by distance-per-time leaves time.",
            "check": check("How long does 40 m take at 5 m/s?", ["8 s", "35 s", "200 s"], "8 s", "t = 40 ÷ 5 = 8 s."),
        },
        {
            "number": 8, "heading": "Average speed", "lead": "The whole journey is summarized by total distance over total elapsed time.",
            "paragraphs": [
                "Real motion often changes. A cyclist may accelerate, cruise, slow, and stop. Instantaneous speed describes one moment, like a speedometer reading now. Average speed summarizes the complete chosen interval: average speed = total distance traveled ÷ total elapsed time.",
                "Suppose a walker covers 100 m in 20 s and another 100 m in 30 s. Total distance is 200 m and total time is 50 s, so average speed is 4 m/s. Simply averaging the stage speeds, 5 m/s and about 3.33 m/s, gives the wrong answer because the stages lasted different times.",
                "For equal time intervals, averaging the stage speeds can happen to agree with total distance divided by total time. That is a special consequence of equal weighting, not the general definition. The reliable method always totals distance and time first.",
                "Two journeys can have the same average speed while looking different. Traveling 60 m in 12 s and traveling 100 m in 20 s both average 5 m/s. Average speed does not reveal every change during the route; it reports the single constant rate that would cover the same total distance in the same total time.",
            ],
            "formula": "average speed = total distance / total elapsed time",
            "key_idea": "Total first, divide second; do not automatically average listed speeds.",
            "check": check("A journey covers 40 m in 10 s, then 60 m in 20 s. What is average speed?", ["3.33 m/s", "3.5 m/s", "7 m/s"], "3.33 m/s", "Use 100 m ÷ 30 s, not the simple average of stage speeds."),
        },
        {
            "number": 9, "heading": "Stops and total journey time", "lead": "Rest time counts when the complete elapsed journey is measured.",
            "paragraphs": [
                "A cyclist travels 2 km in 10 min, rests for 5 min, then travels another 2 km in 10 min. Total distance is 4 km. Total elapsed time is 25 min because the clock continues during the rest. The complete-journey average is 4 km ÷ 25 min = 0.16 km/min.",
                "Ignoring the stop would use only 20 moving minutes and produce 0.20 km/min. That value answers a different question: average speed while moving. Read the wording carefully. Complete trip, departure to arrival, or total elapsed time normally includes stops.",
                "On a distance–time display, a stop appears as a horizontal section. Time continues across the graph while distance remains unchanged. That flat portion lowers the overall average because the denominator grows without additional distance.",
                "A bus stopping for passengers and a runner pausing for water follow the same rule. Record a timeline, label moving and resting intervals, add all required times, and then divide total path length by that total. State explicitly if a problem instead requests moving-time average.",
            ],
            "key_idea": "A stopped object adds zero distance but still adds elapsed time.",
            "check": check("A 10-minute trip includes a 2-minute stop. Which time is used for complete-trip average speed?", ["8 min", "10 min", "2 min"], "10 min", "The complete elapsed interval includes the stop."),
        },
        {
            "number": 10, "heading": "Comparing speeds", "lead": "Convert to common units before ranking motion.",
            "paragraphs": [
                "To compare different objects, express their speeds in the same unit. A runner at 5 m/s and a cyclist at 18 km/h are equally fast because 5 × 3.6 = 18 km/h. Comparing the numbers 5 and 18 without noticing their units would be meaningless.",
                "Realistic estimates help detect mistakes. A comfortable walk is roughly 1–2 m/s, a running student may reach several meters per second, and road vehicles usually have larger values. Context varies, but an answer of thousands of meters per second for a corridor walk demands rechecking units or operations.",
                "Equal-distance comparisons reward shorter time; equal-time comparisons reward greater distance. When both distance and time differ, calculate rates. A bus traveling farther is not automatically faster, and an object moving longer is not automatically faster.",
                "Advanced comparisons may include uncertainty and significant figures. Measurements such as 12.4 m and 3.2 s should not produce a final answer with many unjustified digits. Report a sensible precision while preserving enough digits during intermediate calculations.",
            ],
            "key_idea": "Common units and physical context turn numerical rates into fair comparisons.",
            "check": check("Which is faster: 10 m/s or 36 km/h?", ["10 m/s", "36 km/h", "They are equal"], "They are equal", "10 m/s × 3.6 = 36 km/h."),
        },
        {
            "number": 11, "heading": "Speed versus velocity preview", "lead": "Velocity adds directional change to the rate description.",
            "paragraphs": [
                "Speed tells how fast and uses distance. Velocity tells how fast and in which direction and is connected to displacement. The words are related but not interchangeable. This lesson calculates scalar speed; Lesson 4 will develop velocity carefully.",
                "A runner completing a lap has positive distance and positive average speed, but zero displacement. Therefore the runner's average velocity over the complete lap is zero while average speed is not. This contrast connects directly to Lesson 2 without requiring full velocity calculations yet.",
                "At an instant, a car traveling east at 12 m/s and another traveling west at 12 m/s have the same speed but different velocities. Direction distinguishes the velocities. A speed answer should not attach east, west, positive, or negative as part of the scalar value.",
                "Before choosing a future formula, inspect the words: total path length points to distance and speed, while endpoint change and direction point to displacement and velocity. Keeping those pairs separate prepares you for acceleration and motion graphs.",
            ],
            "key_idea": "Speed pairs with distance; velocity pairs with displacement and direction.",
            "check": check("Two cars move at 8 m/s in opposite directions. What is shared?", ["Velocity", "Speed", "Displacement"], "Speed", "Their scalar speeds match, while directions make velocities different."),
        },
    ],
    "additional_checks": [
        check("True or false: a stopped object has negative speed.", ["True", "False"], "False", "Its speed is zero."),
        check("Which formula finds distance?", ["d = vt", "d = v/t", "d = t/v"], "d = vt", "Rate multiplied by time gives distance."),
        check("Which value is unreasonable for a student walking down a corridor?", ["1.4 m/s", "500 m/s", "5 km/h"], "500 m/s", "Use context to check magnitude."),
    ],
    "video": {
        "title": "How Can We Measure Who Is Faster?", "target_duration": "6–9 minutes", "status": "in production",
        "storyboard": [
            "Hook with a toy-car race.", "Compare the same distance in different times.",
            "Compare different distances in the same time.", "Build speed = distance/time physically.",
            "Interpret m/s and km/h.", "Include a stop in an average-speed journey.",
            "Correct the distance-versus-displacement mistake.", "Connect to Speed Lab and close with a prediction.",
        ],
        "filming_notes": ["Use visible meter and time markers.", "Keep units on screen.", "Pause before every calculation.", "Do not present placeholder footage as finished media."],
    },
    "simulation": {
        "type": "speed_lab", "title": "Speed Lab: Distance, Time and Motion",
        "instruction": "Set distance, speed, and duration; predict, run, pause, compare trials, and inspect a live distance–time representation.",
        "tasks": ["Keep distance constant and change time.", "Keep time constant and change distance.", "Double speed.", "Compare equal-distance trials.", "Compare equal-time trials.", "Create equal-average-speed journeys.", "Add a stop and observe average speed."],
    },
    "worked_examples": [
        {"title": "Example 1: Speed in m/s", "question": "A toy car travels 36 m in 9 s.", "known": "d = 36 m; t = 9 s", "reasoning": "Distance per second requires division.", "steps": ["v = d/t", "v = 36/9", "v = 4 m/s"], "answer": "4 m/s", "common_error": "Do not multiply distance and time."},
        {"title": "Example 2: Speed in km/h", "question": "A bus travels 150 km in 3 h.", "known": "d = 150 km; t = 3 h", "reasoning": "The units already produce km/h.", "steps": ["v = d/t", "150/3 = 50", "Check: 50 × 3 = 150"], "answer": "50 km/h", "common_error": "Keep km with hours."},
        {"title": "Example 3: Distance", "question": "A runner maintains 5 m/s for 12 s.", "known": "v = 5 m/s; t = 12 s", "reasoning": "Each second adds five meters.", "steps": ["d = vt", "d = 5 × 12", "d = 60 m"], "answer": "60 m", "common_error": "Division would not give a distance."},
        {"title": "Example 4: Time", "question": "A cart covers 84 m at 7 m/s.", "known": "d = 84 m; v = 7 m/s", "reasoning": "Find how many seven-meter seconds fit.", "steps": ["t = d/v", "t = 84/7", "t = 12 s"], "answer": "12 s", "common_error": "Speed cannot be zero in this rearrangement."},
        {"title": "Example 5: Compare students", "question": "Sam runs 60 m in 12 s; Ari runs 70 m in 14 s.", "known": "Two distances and times", "reasoning": "Both rates must be calculated.", "steps": ["Sam: 60/12 = 5 m/s", "Ari: 70/14 = 5 m/s", "Their speeds match."], "answer": "Both average 5 m/s", "common_error": "Ari's greater distance alone does not mean faster."},
        {"title": "Example 6: Continuous average", "question": "A cyclist covers 300 m in 40 s then 200 m in 35 s.", "known": "Total d = 500 m; total t = 75 s", "reasoning": "Total first, divide second.", "steps": ["v_avg = 500/75", "v_avg = 6.67 m/s", "The value represents the whole trip."], "answer": "6.67 m/s", "common_error": "Do not simply average stage speeds."},
        {"title": "Example 7: Average with a stop", "question": "A bus covers 4 km in 10 min, stops 5 min, then covers 2 km in 5 min.", "known": "d = 6 km; elapsed t = 20 min", "reasoning": "Complete elapsed time includes the stop.", "steps": ["Add 10 + 5 + 5 = 20 min", "v_avg = 6/20", "v_avg = 0.30 km/min"], "answer": "0.30 km/min", "common_error": "Ignoring the stop answers a different question."},
        {"title": "Example 8: Multi-stage journey", "question": "Walk 90 m in 60 s, then 60 m in 30 s.", "known": "d = 150 m; t = 90 s", "reasoning": "Use totals despite changing speed.", "steps": ["v_avg = 150/90", "v_avg = 1.67 m/s", "Estimate between the stage rates."], "answer": "1.67 m/s", "common_error": "Do not use displacement."},
        {"title": "Example 9: Grade 9 conversion", "question": "Convert 12 m/s to km/h.", "known": "1 m/s = 3.6 km/h", "reasoning": "An hour has 3600 s and a kilometer has 1000 m.", "steps": ["12 × 3.6", "= 43.2", "Attach km/h."], "answer": "43.2 km/h", "common_error": "Do not divide when converting m/s to km/h."},
    ],
    "misconceptions": [
        {"myth": "The object traveling farthest is always fastest.", "why": "Distance feels like performance.", "correction": "Time must also be known.", "example": "100 m in 50 s is slower than 60 m in 10 s.", "quick_check": "What rate does each have?"},
        {"myth": "The object moving longest is always fastest.", "why": "Long activity seems like more motion.", "correction": "Compare distance per time.", "example": "Walking one hour can be slower than cycling ten minutes.", "quick_check": "Is distance known?"},
        {"myth": "Speed uses displacement.", "why": "Both describe a journey.", "correction": "Speed uses total distance.", "example": "One lap has positive average speed despite zero displacement.", "quick_check": "What path length was traveled?"},
        {"myth": "A stopped object has negative speed.", "why": "Stopping feels opposite to moving.", "correction": "Its speed is zero.", "example": "A parked cart adds 0 m each second.", "quick_check": "Can scalar path rate be negative?"},
        {"myth": "Average speed is always the average of listed speeds.", "why": "The word average suggests adding and dividing.", "correction": "Use total distance over total time.", "example": "Unequal time intervals have unequal weight.", "quick_check": "Were the time intervals equal?"},
        {"myth": "Rest time is always ignored.", "why": "No distance is added.", "correction": "Complete elapsed time includes rest.", "example": "A bus clock continues at a stop.", "quick_check": "Does the question say complete trip?"},
        {"myth": "A numerical answer without a unit is complete.", "why": "The calculator gives only a number.", "correction": "A speed needs distance-per-time units.", "example": "5 m/s differs from 5 km/h.", "quick_check": "What units were divided?"},
        {"myth": "Speed and velocity are identical.", "why": "Everyday language mixes them.", "correction": "Velocity includes direction and connects to displacement.", "example": "Opposite-moving cars can share speed.", "quick_check": "Was direction specified?"},
    ],
    "guided_practice": [
        {"question": text, "hints": ["List the given values.", "Name the requested quantity.", "Choose v=d/t, d=vt, or t=d/v.", "Make the units consistent.", "Substitute before calculating.", "Interpret the magnitude and unit."]}
        for text in [
            "Find speed for 48 m in 8 s.", "Find distance at 3 m/s for 14 s.", "Find time for 100 m at 4 m/s.",
            "Compare 80 m in 16 s with 90 m in 20 s.", "Convert 3 minutes to seconds before finding speed for 360 m.",
            "Find average speed for 50 m in 10 s then 100 m in 25 s.", "Include a 5 s rest in a 20 s journey covering 60 m.",
            "Explain why 7 has no meaning as a speed without a unit.", "Decide whether 400 m/s is reasonable for a walker.",
            "Find two distance-time pairs with speed 5 m/s.", "Convert 8 m/s to km/h.", "Explain why a lap uses distance rather than displacement.",
        ]
    ],
    "practice_groups": [
        {"level": "Foundation", "description": "Direct whole-number relationships.", "questions": [
            "Define speed.", "Find speed: 20 m in 5 s.", "Find speed: 45 m in 9 s.", "Find distance: 4 m/s for 6 s.",
            "Find time: 35 m at 5 m/s.", "Choose the unit for meters divided by seconds.",
        ]},
        {"level": "Standard", "description": "Rearrangement, comparisons, and journey totals.", "questions": [
            "Find average speed: 120 m in 30 s then 80 m in 20 s.", "A cyclist covers 2 km in 8 min, rests 2 min, then covers 1 km in 5 min. Find complete-trip average.",
            "Compare 150 m in 25 s with 180 m in 36 s.", "Convert 4 min to seconds and find speed for 600 m.",
            "Correct the claim that 10 m/s for 3 s gives 3.3 m.", "Estimate a realistic walking speed.",
        ]},
        {"level": "Challenge", "description": "Conversions and written reasoning.", "questions": [
            "Convert 15 m/s to km/h.", "Design two journeys with average speed 6 m/s.", "Explain why averaging 2 m/s and 8 m/s may be wrong.",
            "A bus completes equal distances at 30 km/h and 60 km/h. Is average speed 45 km/h? Justify.",
            "Compare an equal-time and equal-distance speed problem.", "Explain speed versus velocity using a round trip.",
        ]},
    ],
    "quiz": [
        {"id": "sq1", "type": "multiple_choice", "objective": "understanding_speed", "question": "What does speed measure?", "options": ["Distance per time", "Displacement only", "Time per direction"], "correct": "Distance per time"},
        {"id": "sq2", "type": "multiple_choice", "objective": "formula_selection", "question": "Which formula finds distance?", "options": ["d = vt", "d = v/t", "d = t/v"], "correct": "d = vt"},
        {"id": "sq3", "type": "multiple_choice", "objective": "speed_velocity", "question": "Which quantity includes direction?", "options": ["Speed", "Velocity", "Distance"], "correct": "Velocity"},
        {"id": "sq4", "type": "multiple_choice", "objective": "calculation", "question": "Speed for 60 m in 12 s?", "options": ["5 m/s", "72 m/s", "0.2 m/s"], "correct": "5 m/s"},
        {"id": "sq5", "type": "multiple_choice", "objective": "calculation", "question": "Distance at 7 m/s for 8 s?", "options": ["56 m", "15 m", "0.875 m"], "correct": "56 m"},
        {"id": "sq6", "type": "multiple_choice", "objective": "calculation", "question": "Time for 90 m at 10 m/s?", "options": ["9 s", "900 s", "80 s"], "correct": "9 s"},
        {"id": "sq7", "type": "multiple_choice", "objective": "units", "question": "Convert 5 m/s to km/h.", "options": ["18 km/h", "1.39 km/h", "50 km/h"], "correct": "18 km/h"},
        {"id": "sq8", "type": "multiple_choice", "objective": "average_speed", "question": "100 m in 20 s then 50 m in 10 s: average speed?", "options": ["5 m/s", "7.5 m/s", "15 m/s"], "correct": "5 m/s"},
        {"id": "sq9", "type": "multiple_choice", "objective": "average_speed", "question": "A 40 s complete trip includes a 10 s stop and covers 120 m. Average speed?", "options": ["3 m/s", "4 m/s", "12 m/s"], "correct": "3 m/s"},
        {"id": "sq10", "type": "multiple_choice", "objective": "reasonable_answer", "question": "Which is a reasonable walking speed?", "options": ["1.5 m/s", "500 m/s", "−3 m/s"], "correct": "1.5 m/s"},
        {"id": "sq11", "type": "written_review", "objective": "average_speed", "question": "Explain why rest time may lower complete-trip average speed.", "options": [], "correct": None},
        {"id": "sq12", "type": "written_review", "objective": "speed_velocity", "question": "Explain why a round trip can have positive average speed but zero average velocity.", "options": [], "correct": None},
    ],
    "mastery_threshold": 80,
    "homework": {
        "title": "Speed Practice Homework", "estimated_time": "25–35 min", "due_date": None,
        "status": "Workspace coming soon", "workspace_available": False,
        "metadata": {"lesson_slug": "speed", "assignment_key": "speed-practice-homework"},
    },
    "summary": [
        "Speed tells how fast an object moves and is a scalar.", "Speed is v = d/t.", "Distance is d = vt.",
        "Time is t = d/v.", "Distance and time units must be compatible.",
        "Average speed uses total distance and total elapsed time.", "Stops may lower complete-trip average speed.",
        "Speed uses distance; velocity is related to displacement and includes direction.",
    ],
    "reflection": "Describe two different journeys that could have the same average speed.",
}
